name: Lint

on: [pull_request]

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: apt install clang-format
      - run: clang-format --version
      - run: |
          make lint
