name: Lint

on: [pull_request]

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format style check for C/C++ programs.
        uses: jidicula/clang-format-action@v4
        with:
          clang-format-version: "18"
          check-path: "src"
          fallback-style: "LLVM"
